/**
 * @file Makes pseudo-dom a drop-in swap for a real DOM: code written against bare globals (document.createElement,
 * new Node(), ...) works unmodified, in the browser or in Node, without an if (typeof document === 'undefined')
 * check at every call site.
 * @author Joshua Heagle <joshuaheagle@gmail.com>
 * @version 1.0.0
 */
import { isBrowser } from 'browser-or-node'
import generateDocument from './generateDocument'

/**
 * When there is no real DOM already available (a real browser, or a jsdom-based test environment - isBrowser is
 * true for both, since jsdom's window has a document too, and a jsdom document should never be overwritten, real
 * DOM behaviour is always closer to the real thing), populate the given global-like target with document / Node /
 * Element / HTMLElement / HTMLDocument, generated by generateDocument, plus window (a self-reference, matching a
 * real browser's global scope - some code checks for a bare `window` before falling back to `global`), so code
 * written against a real DOM's globals works as-is. Does nothing when a real DOM is already there, matching
 * generateDocument's own only-fill-what-is-missing behaviour - calling this is always safe, in any environment.
 * @memberOf module:factories
 * @param {*} [target] The object to add document / Node / Element / HTMLElement / window onto - defaults to
 * globalThis, so bare `document`, `Node`, `window`, etc. resolve from anywhere once this has run
 * @returns {*} The same target, for convenience
 */
const installGlobal = (target: any = typeof globalThis !== 'undefined' ? globalThis : {}): any => {
  if (!isBrowser) {
    generateDocument(target, target)
    if (typeof target.window === 'undefined') {
      target.window = target
    }
  }
  return target
}

export default installGlobal
